# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  # vmImage: ubuntu-latest

variables:
- group: Project03-VariableGroup-Dev

stages:
- stage: BuildAndPublish
  displayName: Build and Publish Application
  jobs:
  - job: BuildApplication
    displayName: Build Application Job
    steps:
    - task: PowerShell@2
      displayName: Build Application
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: 'mvn clean verify'

    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      continueOnError: true
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)\target\solar-system-stock-index.war'
        ArtifactName: 'solar-system-stock-index'
        publishLocation: 'Container'

    - task: CopyFilesOverSSH@0
      displayName: Copy Files to VM (Over SSH)
      inputs:
        sshEndpoint: 'SSH-SC-04JAN2026'
        sourceFolder: '$(System.DefaultWorkingDirectory)\target'
        contents: 'solar-system-stock-index.war'
        targetFolder: '/tmp/app'
        cleanTargetFolder: true
        readyTimeout: '20000'

    - task: SSH@0
      displayName: Copy Files to Tomcat Server
      inputs:
        sshEndpoint: 'SSH-SC-04JAN2026'
        runOptions: 'inline'
        inline: |
          sudo rm -r /var/lib/tomcat9/webapps/solar-system-stock-index.war
          sudo cp /tmp/app/solar-system-stock-index.war /var/lib/tomcat9/webapps
        readyTimeout: '20000'